[theme]
primaryColor = "#00C853" # Verde para combinar com finanças
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"